### ISSUE TITLE
Week 10 Pre-Flight Mini Checklist

### ISSUE THREAD

**Issue by akiwarheit** [akiwarheit/mads-capstone-project#18]
### Project Components
- [x] You have reviewed the [project specifications](https://docs.google.com/document/d/15S0W_qQB2YsKfo7q8ujoilqUDtY18OVvxckc9l4J0dk/edit?usp=sharing)
- [x] You have identified any remaining specifications to complete

### Graphics
- [x] All text on your charts is readable
- [x] Font is not too small (at least 8 pts)
- [x] Text labels are not cut off
- [x] Axes are labeled with informative titles
- [x] Visualizations are interpreted in your written report
- [x] Each chart emphasizes a key idea
- [x] Where possible, avoid raw screenshots (exceptions might be explaining a feature of a dashboard or other product)

### Writing
- [x] Spell check for typos (using a tool of your choice)
- [x] Use a consistent citation format. Direct quotations from other writers are clearly indicated
- [x] Use a consistent style for formatting tables, section headers, and other document elements
- [x] Acronyms and abbreviations are explained the first time they appear
- [x] Watch for jargon—if you think a term or phrase might not be familiar to a broad audience of data professionals, consider adding a short definition

### Code Cleanup
- [x] Unused code has been removed, including:
  - [x] Extra files/scripts
  - [x] Long code blocks
  - [x] Commented out code blocks
- [x] Absolute file paths have been changed to relative paths
- [x] Your repository does not include sensitive information, such as:
  - [x] API keys
  - [x] Credentials for cloud services
  - [x] Sensitive data that should not be shared on GitHub

### Interactive Components
- [x] If your project includes a dashboard, new website, or interactive demo, make sure:
  - [x] All links work
  - [x] All components function as expected (buttons, drop down menus, etc.)
